# Site settings
name: Your Name
title: Your Name | Your Title
description: Your personal description
url: https://mahamfkhan.github.io/cv/
baseurl: '/cv'
email: your.email@example.com
cover: https://mahamfkhan.github.io/cv/img/your-cover-image.png
logo: https://mahamfkhan.github.io/cv/img/your-logo.png
resume: https://mahamfkhan.github.io/cv/your-resume.pdf
social:
  - title: email
    url: mailto:your.email@example.com
  - title: github
    url: https://github.com/mahamfkhan
  - title: linkedin
    url: https://www.linkedin.com/in/your-linkedin-profile

# Build settings
markdown: kramdown
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
keep_files:
  - '.git'
  - '.gitignore'
plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
