# Site settings
name: Maham Faisal Khan
title: Maham F. Khan | Data scientist
description: Your personal description and professional focus
url: https://mahamfkhan.github.io/cv/
baseurl: '/cv'
email: your.email@example.com
cover: https://mahamfkhan.github.io/cv/img/og.png
logo: https://mahamfkhan.github.io/cv/img/emojis/technologist.png
resume: https://mahamfkhan.github.io/cv/resume.pdf
social:
  - title: email
    url: mailto:your.email@example.com
  - title: github
    url: https://github.com/mahamfkhan
  - title: linkedin
    url: https://www.linkedin.com/in/your-linkedin-profile
  # Add or remove other social media as needed

# Build settings
markdown: kramdown
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'
keep_files:
  - '.git'
  - '.gitignore'
plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
