name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Adjust this if needed

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '10.13.0'  # Using the version from your .nvmrc

      - name: Install Ruby dependencies
        run: |
          gem install jekyll sass bundler jekyll-minifier jekyll-sitemap

      - name: Install Node.js dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Adjust this if your build output is in a different directory
